stages:
  - test
  - build
  - deploy

# ENV Vars are define in Gitlab UI at project scope
# variables:
#   AWS_DEFAULT_REGION: 'us-east-1'
#   AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID'
#   AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY'
#   AlertEmail: 'example@example.com'
#   UserName: 'my_username'
#   SshPublicKey: 'ssh-rsa AaA...'

test:
  stage: test
  image: python:3.11
  script:
    - python -m pip install --upgrade pip
    - pip install -r app/requirements.txt
    - python -m unittest discover -s test -p 'test.py'

build:
  stage: build
  image: 'public.ecr.aws/sam/build-python3.11:1.125.0-20240926224215'
  script:
    - sam build
  artifacts:
    paths:
      - .aws-sam

deploy:
  stage: deploy
  image: 'public.ecr.aws/sam/build-python3.11:1.125.0-20240926224215'
  script:
    - |
      sam deploy \
        --no-confirm-changeset \
        --no-fail-on-empty-changeset \
        --capabilities CAPABILITY_NAMED_IAM \
        --parameter-overrides \
          ParameterKey=AlertEmail,ParameterValue=${AlertEmail} \
          ParameterKey=UserName,ParameterValue=${UserName} \
          ParameterKey=SshPublicKey,ParameterValue=${SshPublicKey}
  dependencies:
    - build
  only:
    - master
